# Generated by Django 4.1.4 on 2023-12-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_postmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='image_url',
            field=models.TextField(default='https://aioseo.com/wp-content/uploads/2021/04/how-to-find-and-fix-404-errors-in-wordpress.png.webp'),
        ),
    ]
