# Generated by Django 4.1.4 on 2023-12-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postmodel_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image_url',
            field=models.CharField(default='https://aioseo.com/wp-content/uploads/2021/04/how-to-find-and-fix-404-errors-in-wordpress.png.webp', max_length=500),
        ),
    ]
