# Generated by Django 4.1.4 on 2023-12-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_postmodel_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image_url',
            field=models.CharField(max_length=500),
        ),
    ]
